search = [
    {
        "Key": 145267,
        "Player": {
            "Key": 46113946,
            "Hometown": {"State": "Iowa", "City": "Bettendorf"},
            "FirstName": "Andrew",
            "LastName": "Depaepe",
            "FullName": "Andrew Depaepe",
            "Height": "6-5",
            "Weight": 245.0,
            "Bio": "Andrew Depaepe is a 6-6, 245-pound Strong-Side Defensive End from Bettendorf, IA. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "gcallahan",
            "ModifiedDate": "6/7/2022 2:16:00 PM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Andrew-Depaepe-46113946/",
            "PlayerHighSchool": {"Name": "Pleasant Valley"},
            "LastRecruitmentPlayerInstitution": 262437,
            "CurrentPlayerInstitution": 262437,
            "TwitterContact": 55809,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 272529,
            "PrimaryPlayerPosition": {"Abbreviation": "DL"},
            "PrimaryRecruitment": 145267,
            "DefaultName": "Andrew Depaepe",
            "DefaultAsset": 10682023,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/23/682/10682023.jpeg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Andrew Depaepe is a 6-6, 245-pound Strong-Side Defensive End from Bettendorf, IA. ",
            "CompositeRating": 93.23202509032787,
            "CompositeStarRating": 4,
            "NationalRank": 161,
            "PositionRank": 23,
            "StateRank": 2,
        },
        "PlayerInstitution": 262437,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 61,
        "Institution": 11313,
        "State": 26,
        "PlayerSport": 272529,
        "CompositeStrength": "4",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "HardCommit",
        "HighestRecruitInterestEvent": 350914,
        "CommittedRecruitInterest": 724472,
        "CommittedInstitution": 24043,
        "HighestRecruitInterest": 724472,
        "PrimaryPlayerPosition": 288982,
        "PrimaryPosition": 61,
        "DefaultName": "Andrew Depaepe",
        "CommitedInstitutionTeamImage": "https://s3media.247sports.com/Uploads/Assets/240/483/8483240.png",
        "RecruitInterestCount": 14,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Andrew-Depaepe-145267/RecruitInterests/",
    },
    {
        "Key": 146262,
        "Player": {
            "Key": 46114955,
            "Hometown": {"State": "Florida", "City": "Altamonte Springs"},
            "FirstName": "Andrew",
            "LastName": "Harris",
            "FullName": "Andrew Harris",
            "Height": "6-1",
            "Weight": 200.0,
            "Bio": "Born in Jamaica where he and his twin brother grew up playing soccer ... Also does track and field at the high school level and reports an offer to run/throw for the Naval Academy … As a 10th grader, qualified for Florida’s 4A track meet in the 200-meter dash and the 4x100 (captured silver) … 11th grade track season focused primarily on throwing events (shot put, discus, javelin) … Owns personal bests of 10.72 in the 100-meter dash, a wind-aided 21.50 (2.1) in the 200-meter dash, 20’5-2.5” in the long jump, 36’-4” in the shot put, 80’-8” in the discus and 58’-10” in the javelin. \r\n\r\n2021: Earned third-team all-state recognition from FloridaHSFootball.com … Totaled a team-high 103 tackles for a Lake Brantley squad that competed in the Sunshine State’s highest classification … Also worked in occasionally on offense as a RB/SB.\r\n\r\n2020: Attended Altamonte Springs (Fla.) Lake Brantley where he played American football for the first time.\r\n\r\n-- Andrew Ivins",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "Andrew Ivins",
            "ModifiedDate": "6/1/2022 12:12:49 PM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Andrew-Harris-46114955/",
            "PlayerHighSchool": {"Name": "Lake Brantley"},
            "LastRecruitmentPlayerInstitution": 263604,
            "CurrentPlayerInstitution": 263604,
            "TwitterContact": 54117,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 273699,
            "PrimaryPlayerPosition": {"Abbreviation": "LB"},
            "PrimaryRecruitment": 146262,
            "DefaultName": "Andrew Harris",
            "DefaultAsset": 11023071,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/71/23/11023071.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Born in Jamaica where he and his twin brother grew up playing soccer ... Also does track and field at the high school level and reports an offer to run/throw for the Naval Academy … As a 10th grader, qualified for Florida’s 4A track meet in the 200-meter dash and the 4x100 (captured silver) … 11th grade track season focused primarily on throwing events (shot put, discus, javelin) … Owns personal bests of 10.72 in the 100-meter dash, a wind-aided 21.50 (2.1) in the 200-meter dash, 20’5-2.5” in the long jump, 36’-4” in the shot put, 80’-8” in the discus and 58’-10” in the javelin. \r\n\r\n2021: Earned third-team all-state recognition from FloridaHSFootball.com … Totaled a team-high 103 tackles for a Lake Brantley squad that competed in the Sunshine State’s highest classification … Also worked in occasionally on offense as a RB/SB.\r\n\r\n2020: Attended Altamonte Springs (Fla.) Lake Brantley where he played American football for the first time.\r\n\r\n-- Andrew Ivins",
            "CompositeRating": 92.37022784560763,
            "CompositeStarRating": 4,
            "NationalRank": 190,
            "PositionRank": 13,
            "StateRank": 37,
        },
        "PlayerInstitution": 263604,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 59,
        "Institution": 9418,
        "State": 44,
        "PlayerSport": 273699,
        "CompositeStrength": "4",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "OfficialVisit",
        "HighestRecruitInterestEvent": 354461,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": 797056,
        "PrimaryPlayerPosition": 290438,
        "PrimaryPosition": 59,
        "DefaultName": "Andrew Harris",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 27,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Andrew-Harris-146262/RecruitInterests/",
    },
    {
        "Key": 148840,
        "Player": {
            "Key": 46117476,
            "Hometown": {"State": "Massachusetts", "City": "Milton"},
            "FirstName": "Andrew",
            "LastName": "Rappleyea",
            "FullName": "Andrew Rappleyea",
            "Height": "6-5",
            "Weight": 225.0,
            "Bio": "Andrew Rappleyea is a 6-5, 225-pound Tight End from Milton, MA. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "gcallahan",
            "ModifiedDate": "5/18/2022 9:42:16 AM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Andrew-Rappleyea-46117476/",
            "PlayerHighSchool": {"Name": "Milton Academy"},
            "LastRecruitmentPlayerInstitution": 267748,
            "CurrentPlayerInstitution": 267748,
            "TwitterContact": 56156,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 277844,
            "PrimaryPlayerPosition": {"Abbreviation": "TE"},
            "PrimaryRecruitment": 148840,
            "DefaultName": "Andrew Rappleyea",
            "DefaultAsset": 11017984,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/984/17/11017984.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Andrew Rappleyea is a 6-5, 225-pound Tight End from Milton, MA. ",
            "CompositeRating": 91.48160535117057,
            "CompositeStarRating": 4,
            "NationalRank": 236,
            "PositionRank": 12,
            "StateRank": 4,
        },
        "PlayerInstitution": 267748,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 15,
        "Institution": 24955,
        "State": 20,
        "PlayerSport": 277844,
        "CompositeStrength": "4",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "HardCommit",
        "HighestRecruitInterestEvent": 352022,
        "CommittedRecruitInterest": 749915,
        "CommittedInstitution": 24047,
        "HighestRecruitInterest": 749915,
        "PrimaryPlayerPosition": 295144,
        "PrimaryPosition": 15,
        "DefaultName": "Andrew Rappleyea",
        "CommitedInstitutionTeamImage": "https://s3media.247sports.com/Uploads/Assets/328/648/4648328.png",
        "RecruitInterestCount": 25,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Andrew-Rappleyea-148840/RecruitInterests/",
    },
    {
        "Key": 152891,
        "Player": {
            "Key": 46129544,
            "Hometown": {"State": "Florida", "City": "Palmetto"},
            "FirstName": "Andrew",
            "LastName": "Rumph",
            "FullName": "Andrew Rumph",
            "Height": "6-3.5",
            "Weight": 265.0,
            "Bio": "2021: Transferred into Palmetto (Fla.) for junior year. Had a breakout season, posting 16 TFL and 4 sack to go along with 47 tackles for the Tigers, who went 5-6 and made the playoffs in the Sunshine State's second-highest classification. A FACA All-Area selection and a Sarasota Herald-Tribune All-Area defensive selection.\r\n\r\n2020/2019: Attended Bradenton (Fla.) St. Stephen's Episcopal for freshmen and sophomore seasons.",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "Andrew Ivins",
            "ModifiedDate": "6/10/2022 12:02:23 PM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Andrew-Rumph-46129544/",
            "PlayerHighSchool": {"Name": "Palmetto"},
            "LastRecruitmentPlayerInstitution": 275333,
            "CurrentPlayerInstitution": 275333,
            "TwitterContact": 57448,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 285436,
            "PrimaryPlayerPosition": {"Abbreviation": "DL"},
            "PrimaryRecruitment": 152891,
            "DefaultName": "Andrew Rumph",
            "DefaultAsset": 11023289,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/289/23/11023289.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "2021: Transferred into Palmetto (Fla.) for junior year. Had a breakout season, posting 16 TFL and 4 sack to go along with 47 tackles for the Tigers, who went 5-6 and made the playoffs in the Sunshine State's second-highest classification. A FACA All-Area selection and a Sarasota Herald-Tribune All-Area defensive selection.\r\n\r\n2020/2019: Attended Bradenton (Fla.) St. Stephen's Episcopal for freshmen and sophomore seasons.",
            "CompositeRating": 86.92592592592592,
            "CompositeStarRating": 3,
            "NationalRank": 700,
            "PositionRank": 82,
            "StateRank": 102,
        },
        "PlayerInstitution": 275333,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 61,
        "Institution": 9247,
        "State": 44,
        "PlayerSport": 285436,
        "CompositeStrength": "3",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "OfficialVisit",
        "HighestRecruitInterestEvent": 355328,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": 794737,
        "PrimaryPlayerPosition": 303841,
        "PrimaryPosition": 61,
        "DefaultName": "Andrew Rumph",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 18,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Andrew-Rumph-152891/RecruitInterests/",
    },
    {
        "Key": 151597,
        "Player": {
            "Key": 46128326,
            "Hometown": {"State": "Colorado", "City": "Aurora"},
            "FirstName": "Andrew",
            "LastName": "Metzger",
            "FullName": "Andrew Metzger",
            "Height": "6-5",
            "Weight": 235.0,
            "Bio": "Andrew Metzger is a 6-5, 235-pound Tight End from Aurora, CO. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "gcallahan",
            "ModifiedDate": "5/25/2022 8:57:22 AM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Andrew-Metzger-46128326/",
            "PlayerHighSchool": {"Name": "Regis Jesuit"},
            "LastRecruitmentPlayerInstitution": 273458,
            "CurrentPlayerInstitution": 273458,
            "TwitterContact": 56813,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 283558,
            "PrimaryPlayerPosition": {"Abbreviation": "TE"},
            "PrimaryRecruitment": 151597,
            "DefaultName": "Andrew Metzger",
            "DefaultAsset": 10713615,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/615/713/10713615.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Andrew Metzger is a 6-5, 235-pound Tight End from Aurora, CO. ",
            "CompositeRating": 84.52777777777777,
            "CompositeStarRating": 3,
            "NationalRank": 1126,
            "PositionRank": 56,
            "StateRank": 8,
        },
        "PlayerInstitution": 273458,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 15,
        "Institution": 940,
        "State": 40,
        "PlayerSport": 283558,
        "CompositeStrength": "4",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "HardCommit",
        "HighestRecruitInterestEvent": 352276,
        "CommittedRecruitInterest": 757059,
        "CommittedInstitution": 24020,
        "HighestRecruitInterest": 757059,
        "PrimaryPlayerPosition": 301555,
        "PrimaryPosition": 15,
        "DefaultName": "Andrew Metzger",
        "CommitedInstitutionTeamImage": "https://s3media.247sports.com/Uploads/Assets/440/649/4649440.png",
        "RecruitInterestCount": 23,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Andrew-Metzger-151597/RecruitInterests/",
    },
    {
        "Key": 137781,
        "Player": {
            "Key": 46100159,
            "Hometown": {"State": "Oklahoma", "City": "Norman"},
            "FirstName": "Parker",
            "LastName": "Andrews",
            "FullName": "Parker Andrews",
            "Height": "6-4",
            "Weight": 225.0,
            "Bio": "Parker Andrews is a Defensive End from Norman, OK. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "Cody Nagel",
            "ModifiedDate": "4/9/2022 9:00:45 AM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Parker-Andrews-46100159/",
            "PlayerHighSchool": {"Name": "Norman North"},
            "LastRecruitmentPlayerInstitution": 249025,
            "CurrentPlayerInstitution": 249025,
            "TwitterContact": 49255,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 259083,
            "PrimaryPlayerPosition": {"Abbreviation": "DL"},
            "PrimaryRecruitment": 137781,
            "DefaultName": "Parker Andrews",
            "DefaultAsset": 11027166,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/166/27/11027166.jpeg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Parker Andrews is a Defensive End from Norman, OK. ",
            "CompositeRating": None,
            "CompositeStarRating": 0,
            "NationalRank": None,
            "PositionRank": None,
            "StateRank": None,
        },
        "PlayerInstitution": 249025,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 61,
        "Institution": 18657,
        "State": 29,
        "PlayerSport": 259083,
        "CompositeStrength": "0",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "0",
        "HighestRecruitInterestEvent": None,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": None,
        "PrimaryPlayerPosition": 273157,
        "PrimaryPosition": 61,
        "DefaultName": "Parker Andrews",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 0,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Parker-Andrews-137781/RecruitInterests/",
    },
    {
        "Key": 148333,
        "Player": {
            "Key": 46116987,
            "Hometown": {"State": "Texas", "City": "San Antonio"},
            "FirstName": "TJ",
            "LastName": "Andrews",
            "FullName": "TJ Andrews",
            "Height": "6-1",
            "Weight": 195.0,
            "Bio": "TJ Andrews is a Running Back from San Antonio, TX. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "gcallahan",
            "ModifiedDate": "5/23/2022 4:00:27 PM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/TJ-Andrews-46116987/",
            "PlayerHighSchool": {"Name": "Taft"},
            "LastRecruitmentPlayerInstitution": 266921,
            "CurrentPlayerInstitution": 266921,
            "TwitterContact": 55067,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 277016,
            "PrimaryPlayerPosition": {"Abbreviation": "RB"},
            "PrimaryRecruitment": 148333,
            "DefaultName": "TJ Andrews",
            "DefaultAsset": 11056012,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/12/56/11056012.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "TJ Andrews is a Running Back from San Antonio, TX. ",
            "CompositeRating": None,
            "CompositeStarRating": 0,
            "NationalRank": None,
            "PositionRank": None,
            "StateRank": None,
        },
        "PlayerInstitution": 266921,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 12,
        "Institution": 21438,
        "State": 9,
        "PlayerSport": 277016,
        "CompositeStrength": "0",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "0",
        "HighestRecruitInterestEvent": None,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": None,
        "PrimaryPlayerPosition": 294224,
        "PrimaryPosition": 12,
        "DefaultName": "TJ Andrews",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 5,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/TJ-Andrews-148333/RecruitInterests/",
    },
    {
        "Key": 153587,
        "Player": {
            "Key": 46130600,
            "Hometown": {"State": "Ohio", "City": "Barberton"},
            "FirstName": "Roosevelt",
            "LastName": "Andrews",
            "FullName": "Roosevelt Andrews",
            "Height": "6-2",
            "Weight": 215.0,
            "Bio": "Roosevelt Andrews is a 6-2, 215-pound Linebacker from Barberton, OH. ",
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "AllenTrieu",
            "ModifiedDate": "2/16/2022 9:28:30 AM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Roosevelt-Andrews-46130600/",
            "PlayerHighSchool": {"Name": "Barberton"},
            "LastRecruitmentPlayerInstitution": 276398,
            "CurrentPlayerInstitution": 276398,
            "TwitterContact": None,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 286501,
            "PrimaryPlayerPosition": {"Abbreviation": "LB"},
            "PrimaryRecruitment": 153587,
            "DefaultName": "Roosevelt Andrews",
            "DefaultAsset": 10920961,
            "DefaultAssetUrl": "https://s3media.247sports.com/Uploads/Assets/961/920/10920961.jpg",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Roosevelt Andrews is a 6-2, 215-pound Linebacker from Barberton, OH. ",
            "CompositeRating": None,
            "CompositeStarRating": 0,
            "NationalRank": None,
            "PositionRank": None,
            "StateRank": None,
        },
        "PlayerInstitution": 276398,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 60,
        "Institution": 17656,
        "State": 14,
        "PlayerSport": 286501,
        "CompositeStrength": "0",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "0",
        "HighestRecruitInterestEvent": None,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": None,
        "PrimaryPlayerPosition": 305046,
        "PrimaryPosition": 59,
        "DefaultName": "Roosevelt Andrews",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 9,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Roosevelt-Andrews-153587/RecruitInterests/",
    },
    {
        "Key": 154768,
        "Player": {
            "Key": 46131744,
            "Hometown": {"State": "California", "City": "Visalia"},
            "FirstName": "Taaj",
            "LastName": "Andrews",
            "FullName": "Taaj Andrews",
            "Height": "5-11",
            "Weight": 315.0,
            "Bio": None,
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "JacksonMoore",
            "ModifiedDate": "3/15/2022 4:09:28 PM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Taaj-Andrews-46131744/",
            "PlayerHighSchool": {"Name": None},
            "LastRecruitmentPlayerInstitution": 277906,
            "CurrentPlayerInstitution": 277906,
            "TwitterContact": None,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 288000,
            "PrimaryPlayerPosition": {"Abbreviation": "DL"},
            "PrimaryRecruitment": 154768,
            "DefaultName": "Taaj Andrews",
            "DefaultAsset": None,
            "DefaultAssetUrl": "/.",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Taaj Andrews is a 5-11, 315-pound Defensive Line from Visalia, CA. ",
            "CompositeRating": None,
            "CompositeStarRating": 0,
            "NationalRank": None,
            "PositionRank": None,
            "StateRank": None,
        },
        "PlayerInstitution": 277906,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 61,
        "Institution": 23671,
        "State": 24,
        "PlayerSport": 288000,
        "CompositeStrength": "0",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "0",
        "HighestRecruitInterestEvent": None,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": None,
        "PrimaryPlayerPosition": 306805,
        "PrimaryPosition": 61,
        "DefaultName": "Taaj Andrews",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 0,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Taaj-Andrews-154768/RecruitInterests/",
    },
    {
        "Key": 157168,
        "Player": {
            "Key": 46134074,
            "Hometown": {"State": "Michigan", "City": "Grand Rapids"},
            "FirstName": "Curtis",
            "LastName": "Andrews",
            "FullName": "Curtis Andrews",
            "Height": "5-11",
            "Weight": 200.0,
            "Bio": None,
            "ScoutEvaluation": None,
            "Birthdate": None,
            "ModifiedUser": "AllenTrieu",
            "ModifiedDate": "5/24/2022 10:05:52 AM",
            "CBSKey": 0,
            "Url": "https://247sports.com/Player/Curtis-Andrews-46134074/",
            "PlayerHighSchool": {"Name": "Forest Hills Northern"},
            "LastRecruitmentPlayerInstitution": 281615,
            "CurrentPlayerInstitution": 281615,
            "TwitterContact": None,
            "MobilePhoneContact": None,
            "PrimaryPlayerSport": 291707,
            "PrimaryPlayerPosition": {"Abbreviation": "ATH"},
            "PrimaryRecruitment": 157168,
            "DefaultName": "Curtis Andrews",
            "DefaultAsset": None,
            "DefaultAssetUrl": "/.",
            "HeroAsset": None,
            "QuoteAsset": None,
            "User": None,
            "ProStatPlayer": None,
            "CollegeStatPlayer": None,
            "BioOrDefault": "Curtis Andrews is a 5-11, 200-pound Athlete from Grand Rapids, MI. ",
            "CompositeRating": None,
            "CompositeStarRating": 0,
            "NationalRank": None,
            "PositionRank": None,
            "StateRank": None,
        },
        "PlayerInstitution": 281615,
        "Year": 2023,
        "AnnouncementDate": None,
        "SignedInstitution": None,
        "Position": 26,
        "Institution": 13222,
        "State": 27,
        "PlayerSport": 291707,
        "CompositeStrength": "0",
        "FinalChoice": None,
        "HighestRecruitInterestEventType": "0",
        "HighestRecruitInterestEvent": None,
        "CommittedRecruitInterest": None,
        "CommittedInstitution": None,
        "HighestRecruitInterest": None,
        "PrimaryPlayerPosition": 310982,
        "PrimaryPosition": 26,
        "DefaultName": "Curtis Andrews",
        "CommitedInstitutionTeamImage": None,
        "RecruitInterestCount": 1,
        "RecruitInterestsUrl": "https://247sports.com/Recruitment/Curtis-Andrews-157168/RecruitInterests/",
    },
]


new = sorted(
    search,
    key=lambda player: int(player["Player"]["CompositeRating"])
    if player["Player"]["CompositeRating"] is not None
    else 0.0,
    reverse=True,
)

for player in new:
    print(player["Player"]["CompositeRating"])

print(search)
